version: '3.7'

services:

  react_gui:
    container_name: email_marketing_gui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 5003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true