version: '3.7'

services:

  sample:
    container_name: react_1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true